FROM node:22-alpine AS builder

WORKDIR /app

# Copia package.json primeiro 
COPY package*.json ./

# Instala as dependências
RUN npm install --legacy-peer-deps

# Copia o restante do projeto
COPY . .

# Compila o Angular para produção
RUN npm run build -- --configuration production


FROM nginx:1.27-alpine AS runtime

# Remove configuração padrão do Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia nossa configuração customizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos compilados pelo Angular
# Angular 21 gera o build em dist/mybuddy/browser
COPY --from=builder /app/dist/mybuddy/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]