services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    pull_policy: if_not_present
    container_name: keycloak-mybuddy
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080

